services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-learning_db}
      POSTGRES_USER: ${DB_USER:-myuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-mypass}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL_LOCAL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      PORT: 5000
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npx ts-node dist/scripts/seed.js && npx ts-node dist/scripts/createAdmin.js && npm run start"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api
    restart: always 
    ports: 
      - "5173:5173" 
    depends_on: 
      - backend 
    environment:
      BACKEND_URL: http://backend:5000

volumes:
  db_data: